"""Generate embedded demo data (web/weather_demo_data.js) for the pure-JS browser demo.

Takes t2m from the downloaded global zarr: N_STEPS timesteps at low res (every RES px),
packs as a base64 Float32Array so the demo page has zero external data dependency.
"""
import os, sys, base64, struct
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import numpy as np
import zarr

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(BASE, "data", "era5_global_7d.zarr")
OUT = os.path.join(BASE, "web", "weather_demo_data.js")

N_STEPS = 8      # 嵌入的时次数
RES = 4          # 空间降采样 (4 -> 1°, 控制页面体积)


def main():
    src = zarr.open(SRC, mode="r")
    n_lat, n_lon = 721, 1440
    lat = np.linspace(90.0, -90.0, n_lat)[::RES]
    lon = np.arange(0.0, 360.0, 0.25)[:n_lon][::RES]
    h, w = len(lat), len(lon)
    ti = np.asarray(src["time_index"])
    idx = np.linspace(0, len(ti) - 1, N_STEPS, dtype=int)

    import json
    from datetime import datetime, timedelta
    T0 = datetime(1940, 1, 1)

    frames = []
    for t in idx:
        a = np.asarray(src["t2m"][t][::RES, ::RES], dtype="float32") - 273.15  # K->C
        b = base64.b64encode(a.tobytes()).decode("ascii")
        frames.append(b)
        print(f"  t={ti[t]} {t_to_str(ti[t])}  finite={np.isfinite(a).mean():.2f}")

    times = [t_to_str(int(ti[t])) for t in idx]
    payload = {
        "h": h, "w": w,
        "lat": [round(float(x), 3) for x in lat],
        "lon": [round(float(x), 3) for x in lon],
        "times": times,
        "frames": frames,  # base64 little-endian float32, row-major (lat,lon)
        "cmin": 10.0, "cmax": 35.0,  # °C 显示窗口 (赤道暖/极区冷)
    }
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    js = "// Auto-generated by scripts/make_web_data.py — do not edit.\nwindow.WS_DATA = " + json.dumps(payload) + ";\n"
    with open(OUT, "w") as f:
        f.write(js)
    print(f"wrote {OUT} ({os.path.getsize(OUT)/1e6:.2f} MB)")


def t_to_str(t):
    from datetime import datetime, timedelta
    return (datetime(1940, 1, 1) + timedelta(hours=int(t))).strftime("%Y-%m-%d %H:%M")


if __name__ == "__main__":
    main()
